nhnacademy-be10-1lluwa/bookstore-product-service

pom.xml
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/BookControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_book/tag/controller/AdminTagControllerTest.java

fix: test code 수정

---

src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/dto/ReviewRequest.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java

- 프론트 연동문제로 이미지 업로드 방식 변경
- 리뷰 수정시 데이터 가져오기용으로 리뷰 상세 페이지 추가 
- Closed: #233

[REFACTOR] 이미지 업로드 방식 변경

---

src/main/java/com/nhnacademy/illuwa/cart/controller/CartController.java

feat: url 변경

---

src/main/java/com/nhnacademy/illuwa/ProductServiceApplication.java
src/test/java/com/nhnacademy/illuwa/ProductServiceApplicationTests.java

- application 이름 변경
- Closed: #

refact: application 이름 변경

---

src/main/java/com/nhnacademy/illuwa/common/exception/GlobalExceptionHandler.java
src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/dto/ReviewRequest.java
src/main/java/com/nhnacademy/illuwa/d_review/review/entity/ReviewImage.java
src/main/java/com/nhnacademy/illuwa/d_review/review/repository/ReviewRepository.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java

- 예외추가/ 리퀘스트변경/ 이미지 컬럼 변경 
- Closed: #248

[REFACTOR] 프론트 연동 관련 수정 

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java

- 도서 등록일 순으로 정렬 추가
> 도서 등록일 순으로 정렬 추가
- 
- Closed: #277

[REFACTOR] 도서 등록일 순 정렬 추가

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java

- Controller Mapping 수정
- Patch -> Put
- Closed: #280

fix: Controller Mapping 수정(Patch -> Put)

---

pom.xml
src/main/java/com/nhnacademy/illuwa/search/document/BookDocument.java
src/main/java/com/nhnacademy/illuwa/search/service/BookSearchService.java
src/main/resources/elasticsearch/books-mapping.json
src/main/resources/elasticsearch/nori-settings.json

- 도서 Elasticsearch document 수정
- `BookDocument` 필드 및 어노테이션 개선
- 검색 Query 로직 수정
- multi_match 필드 및 analyzer 적용 개선
- Elasticsearch client 라이브러리 추가
- `elasticsearch-java` 라이브러리 의존성 설정
- 분석기 JSON 설정 파일 수정
- `nori`, `jaso`, `icu` analyzer 설정 보완
- Closed: #

[REFACTOR] 도서 검색 api 연동 수정

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java

infra: 배포 최신화

---

src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java

- 기존 bookId, true Map<Long, Boolean> 대신 Map<Long, Long> bookId, reviewId 로 이렇게 리턴하도록 api 새로 추가 
기존 api 제거 요망
- Closed: #296

feat: 존재하는 리뷰 확인 api 새롭게 추가

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookmarkController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookmarkResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/entity/Bookmark.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookmarkRepository.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookmarkService.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/Impl/BookmarkServiceImpl.java

[FEAT] Bookmark

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java

fix: 페이징 처리 기존 로직 사용

---

src/main/java/com/nhnacademy/illuwa/d_review/comment/controller/CommentController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/dto/ReviewResponse.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/service/Impl/ReviewLikeServiceImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/service/ReviewLikeService.java
src/main/java/com/nhnacademy/illuwa/infra/storage/FileUploadController.java

- books 계층구조 -> requestparam으로 bookId만 받아옴
- minio 컨트롤러 '/api' 누락 -> 추가
- 리뷰 좋아요 부분 querydsl 안쓰면 추후 삭제 예정  
- Closed: #305

[REFACTOR] 컨트롤러 매핑 경로 수정 

---

src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailWithExtraInfoResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java

- isGiftWrap -> GiftWrap 수정 반영
- Mapper에서는 필드명에 is가 붙었을 때 문제해결
- getter 메서드 변경(isGiftWrap -> getGiftWrap)
- 상세페이지 에러 해결
- . 
- 
- Closed: #

[BUG] 도서 상세페이지 관련 에러

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepositoryCustom.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java

- 도서 삭제 시 검색 엔진에 반영이 안되는 issue 해결
- 중복된 도서 제거 api에서 도서 검색 엔진과 동기화 로직이 추가된 부분으로 변경
- 중복된 로직은 삭제처리
- Closed: #

[FIX] 도서 삭제 api 변경

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/repository/Impl/ReviewQuerydslRepositoryImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java
src/main/java/com/nhnacademy/illuwa/infra/storage/FileUploadController.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewDtoUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewEntityUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewImageEntityUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewQuerydslRepositoryTest.java

- 리뷰 서비스 제외 리뷰쪽 작성 
- Closed: #340

[FEAT] 프론트 동기화용 - 테스트코드 1차업로드 

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/ExternalBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepositoryCustom.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/Impl/BookRepositoryCustomImpl.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/BookControllerTest.java

•기존 POST → PATCH 등 RESTful 방식에 맞게 메서드 변경
•URI 설계 및 HTTP Method를 REST 원칙에 맞게 전반적 리팩토링
•/api/external-books 경로로 분리하여 관심사 분리 (Aladin API 요청)
•추후 삭제 예정인 미사용 API들 주석 처리
- Closed: #343

[REFACTOR] RESTful API 형식 리팩토링

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java

- api 경로 수정
- 테스트 코드 수정
- Closed: #

[REFACTOR] RESTful api 반영 경로 수정 

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
src/main/java/com/nhnacademy/illuwa/infra/storage/FileUploadController.java
src/main/java/com/nhnacademy/illuwa/infra/storage/MinioStorageService.java

- minio delete logic edited
- Closed: #348

[FIX] minio delete logic edited

---

src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
src/test/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryControllerTest.java

- Category 부분 endpoint 수정
- Closed: #

[REFACTOR] 카테고리 Endpoint 수정

---

src/main/java/com/nhnacademy/illuwa/common/client/order/OrderServiceClient.java

refactor: client 코드 수정

---

src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java

- endpoint path 수정
- Closed: #

[REFACTOR] 도서 검색 api endpoint 수정

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java

- swagger 어노테이션 추가 
- Closed: #355

[FEAT] swagger-annotation

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/ExternalBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookApiRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookCountUpdateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookUpdateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BestSellerResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailWithExtraInfoResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookExternalResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/SimpleBookResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepository.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/Impl/BookRepositoryCustomImpl.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/PublicCategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryCreateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryFlatResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/category/repository/category/CategoryRepository.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/AdminTagController.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/TagController.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/repository/BookTagRepository.java
src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java
src/main/java/com/nhnacademy/illuwa/search/document/BookDocument.java

[FEAT] @Swagger 추가

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/ExternalBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookApiRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookCountUpdateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookUpdateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BestSellerResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailWithExtraInfoResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookExternalResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/SimpleBookResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepository.java
src/main/java/com/nhnacademy/illuwa/d_book/book/repository/Impl/BookRepositoryCustomImpl.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/PublicCategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryCreateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryFlatResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/category/repository/category/CategoryRepository.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/AdminTagController.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/TagController.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/repository/BookTagRepository.java
src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java
src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java
src/main/java/com/nhnacademy/illuwa/search/document/BookDocument.java

Revert: Swagger setting PR merges

---

src/main/java/com/nhnacademy/illuwa/cart/controller/CartController.java

feat: cart swagger

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/controller/ExternalBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/AladinBookRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookApiRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookCountUpdateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookSearchRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookUpdateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/FinalAladinBookRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BestSellerResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailWithExtraInfoResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookExternalResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/SimpleBookResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/book/entity/Book.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/PublicCategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryCreateRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryFlatResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryResponse.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/AdminTagController.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/TagController.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagRegisterRequest.java
src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagResponse.java
src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java
src/test/java/com/nhnacademy/illuwa/search/service/BookSearchServiceTest.java

> 이전에 등록한 Swagger 재추가
- Closed: #

[FEAT] Swagger 등록 

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_book/book/service/BookServiceTest.java

> api 명세 수정
> 도서 수량 변경 로직 일원화(환불(+) - 차감(-))
- Closed: #

[FIX] 도서 수량 api 로직 수정

---

pom.xml
src/main/java/com/nhnacademy/illuwa/d_book/book/mapper/BookMapper.java
src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
src/main/java/com/nhnacademy/illuwa/d_book/category/repository/category/CategoryRepository.java
src/main/java/com/nhnacademy/illuwa/d_book/category/service/CategoryService.java
src/test/java/com/nhnacademy/illuwa/d_book/category/service/CategoryServiceTest.java

> 사용하지 않는 코드 제거
> 테스트 코드를 위해 로직 위치 변경
> Category pagination (관리자 페이지) 에러. ㅐ결
- Closed: #374

[Bug] 카테고리 pagination 관련 에러 

---

src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
src/test/java/com/nhnacademy/illuwa/d_book/book/service/BookServiceTest.java
src/test/java/com/nhnacademy/illuwa/d_book/category/service/CategoryServiceTest.java

- BookService 계층 테스트 코드 추가
- CategoryService 계층 테스트 코드 추가
- Closed: #

[FEAT] 테스트 코드 추가

---

src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/repository/Impl/ReviewLikeQuerydslRepositoryImpl.java
src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/service/Impl/ReviewLikeServiceImpl.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewEntityUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewImageEntityUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewServiceUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/reviewlike/ReviewLikeControllerTest.java
src/test/java/com/nhnacademy/illuwa/d_review/reviewlike/ReviewLikeEntityUnitTest.java
src/test/java/com/nhnacademy/illuwa/d_review/reviewlike/ReviewLikeQuerydslRepositoryTest.java
src/test/java/com/nhnacademy/illuwa/d_review/reviewlike/ReviewLikeServiceUnitTest.java

[FEAT] 리뷰, 리뷰좋아요 테스트 코드 

---

src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java

> 카테고리 부분 cache control 추가
- Closed: #

feat: cache control 추가

---

pom.xml

refactor: Qclass 저장위치 수정
